# Generated by Django 2.1.2 on 2018-10-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroaluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfessorDAL',
            new_name='AlunoDAL',
        ),
    ]
