# Generated by Django 2.1.2 on 2018-10-31 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscricao',
            new_name='ProfessorDAL',
        ),
    ]
